### ISSUE TITLE
Error while using the Authorize method

### ISSUE THREAD

**Issue by vaibhav22oct** [AliBazzi/IdentityServer3.Contrib.RedisStore#1]
options.Factory.Register(new Registration<RedisStoreMultiplexer>(new RedisStoreMultiplexer("127.0.0.1:6379")));

            options.Factory.Register(new Registration<IDatabaseAsync>(resolver => resolver.Resolve<RedisStoreMultiplexer>().GetDatabase()));

            options.Factory.AuthorizationCodeStore = new Registration<IAuthorizationCodeStore, AuthorizationCodeStore>();

            options.Factory.TokenHandleStore = new Registration<ITokenHandleStore, TokenHandleStore>();

            options.Factory.RefreshTokenStore = new Registration<IRefreshTokenStore, RefreshTokenStore>();

            options.Factory.UserService = new Registration<IUserService, CustomIdentityUserService>();

causing following error.

{"Message":"An error has occurred.","ExceptionMessage":"An error occurred when trying to create a controller of type 'AuthorizeEndpointController'. Make sure that the controller has a parameterless public constructor.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at System.Web.Http.Tracing.Tracers.HttpControllerActivatorTracer.<>c__DisplayClass2.<System.Web.Http.Dispatcher.IHttpControllerActivator.Create>b__0() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.TraceBeginEnd(ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Action execute, Action`1 endTrace, Action`1 errorTrace) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at System.Web.Http.Tracing.Tracers.HttpControllerActivatorTracer.System.Web.Http.Dispatcher.IHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at System.Web.Http.Tracing.Tracers.HttpControllerDescriptorTracer.<>c__DisplayClass2.<CreateController>b__0() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.TraceBeginEnd(ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Action execute, Action`1 endTrace, Action`1 errorTrace) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at System.Web.Http.Tracing.Tracers.HttpControllerDescriptorTracer.CreateController(HttpRequestMessage request) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'IdentityServer3.Contrib.RedisStores.TokenHandleStore' can be invoked with the available services and parameters:\r\nCannot resolve parameter 'StackExchange.Redis.IDatabase redis' of constructor 'Void .ctor(IdentityServer3.Core.Services.IScopeStore, StackExchange.Redis.IDatabase, IdentityServer3.Contrib.RedisStores.RedisOptions)'.\r\nCannot resolve parameter 'StackExchange.Redis.IDatabase redis' of constructor 'Void .ctor(IdentityServer3.Core.Services.IScopeStore, StackExchange.Redis.IDatabase)'.","ExceptionType":"Autofac.Core.DependencyResolutionException","StackTrace":"   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Registration.ExternalRegistrySource.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.ResolvedParameter.<>c__DisplayClass6`1.<ForKeyed>b__5(ParameterInfo pi, IComponentContext c) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.ResolvedParameter.<>c__DisplayClass2.<CanSupplyValue>b__0() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Registration.ExternalRegistrySource.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, Parameter[] parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at IdentityServer3.Core.Configuration.Hosting.AutofacConfig.<>c__DisplayClass13`2.<RegisterDecorator>b__12(IComponentContext ctx) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\Hosting\\AutoFacConfig.cs:line 233\r\n   at Autofac.RegistrationExtensions.<>c__DisplayClass10`1.<Register>b__f(IComponentContext c, IEnumerable`1 p) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Registration.ExternalRegistrySource.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass2.<CanSupplyValue>b__0() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Registration.ExternalRegistrySource.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass2.<CanSupplyValue>b__0() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Registration.ExternalRegistrySource.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass2.<CanSupplyValue>b__0() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Registration.ExternalRegistrySource.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at Autofac.Integration.WebApi.AutofacWebApiDependencyScope.GetService(Type serviceType) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1& activator) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType) in c:\\local\\identity\\server3\\IdentityServer3\\source\\Core\\Configuration\\DiscoveryOptions.cs:line 0"}}

**Comment by vaibhav22oct** [comment]
I don't know what I will need to change

**Comment by AliBazzi** [comment]
your code that is registering the services is faulty, it looks like the registration for the IDatabase resolver is wrong, maybe the order is wrong, please provide the full source code for identity server registration in order to be able to help and advice more
