### ISSUE TITLE
I want you to be able to set the customprefix in the key of the Redis store

### ISSUE THREAD

**Issue by karuakun** [AliBazzi/IdentityServer3.Contrib.RedisStore#2]
There are already data of multiple projects in Redis.
I want you to be able to attach a prefix to the key of Redis store, to avoid collision.

**Comment by AliBazzi** [comment]
I'm not sure what the scenario you have, do you mean by "multiple projects" that you have multiple tenants ? or you are persisting other data from other different applications in the same store ?
have you considered persisting these operational data for identity server in dedicated Redis DB ?

let me understand more your scenario

**Comment by karuakun** [comment]
thanks.
I'm scenario is persisting other data from other different applications in the same store.
examined storing operation data in dedicated Redis DB. However, because the operation cost increases, I would like to use the same DB.

**Comment by AliBazzi** [comment]
alright, for that, the current key schema that is persisted is like the following:
https://github.com/AliBazzi/IdentityServer3.Contrib.RedisStore/blob/master/IdentityServer3.Contrib.RedisStore/Stores/BaseTokenStore.cs#L29
so it starts basically with token type, represented as a number (1,2 or 3) appended by ":" and the token key that is passed by identity server itself, so I think the collision chance are rare with this schema.

if you still need such prefix, you can work on it and do PR, or I will do it whenever I have the chance. 

Cheers.
