### ISSUE TITLE
Keys in Set does not have TokenType

### ISSUE THREAD

**Issue by Kahbazi** [AliBazzi/IdentityServer3.Contrib.RedisStore#4]
Hi

I think there is a problem on `BaseTokenStore.GetAllAsync` and `BaseTokenStore.RevokeAsync` because the tokens are not returned and I think the reason is the members that are added in `Set` (TokenType:SubjectId) and `Set` (TokenType:SubjectId:ClientId) is only key for token and not its token type.

I study your code and change `BaseTokenStore.StoreAsync`, I insert the actual token key which is `token type:key` on `Set` and now it works for me.
I will create a new Pull Request. 

Let me know what you think. Thanks.

**Comment by AliBazzi** [comment]
Nuget package with version 1.1.4 pushed to nuget.org accordingly.
